### ISSUE TITLE
Splitting CaseManagement.CMMN

### ISSUE THREAD

**Issue by DerekGn** [simpleidserver/CaseManagement#31]
Hi,

I am currently evaluating open source CMMN engines for use in a project. The options I am reviewing at the moment are:

* CaseManagement.CMMN
* Camundra

With Camundra the engine is Java based and would mean interop with our .Net stack via its Rest API. Which is an ok solution but not ideal. It would also be a black box as the team has limited java exposure and there is no budget for an enterprise license.

With the CaseManagement.CMMN component there is a problem with the current structure of the code, for example the interfaces for the repositories, for a production system there would need to be durable implementations created, for example to use SQL server or cosmos db.

The problem is as it stands this would create a circular reference CaseManagement.CMMN -> CaseManagment.Persistance.Sql (The new Sql server implementations)  -> CaseManagement.CMMN

I have already split the project up to work around this issue, in an azure devops repo, but that would basically mean that I have forked completely await from the root project which is far from ideal.

My question is would you be interested splitting out the CaseManagement.CMMN engine into a separate repo and accepting back the project structure refactoring changes?

There are a few other enhancements made to the code that could also be pushed back in to the main repo like logging, unit tests and a few additional checks.

Also would you mind answering a few technical Q's by the way of support that we (the small project team ~ 3) may have when we start using the component in anger?

BTW FWIW This is really a nice project and I think it has great potential as a java CMMN alternative.

**Comment by simpleidserver** [comment]
Hi,

We are currently working on the SQL persistence layer and we are also updating the Case workflow Engine. 
The changes are already present in the branch "release/1.0.3". In the next version, it will be possible for developers to create and launch "CasePlanInstance" with a fluent API.
You can find an example here : https://github.com/simpleidserver/CaseManagement/blob/release/1.0.3/tests/CaseManagement.CMMN.Tests/CaseJobServerFixture.cs
A pre-release version will be published next week, between wednesday and friday. The following changes will be included :

- Persistence layer : SQL
- New case engine

Starting from next week, we can work together and continue to improve the Case Management solution : logging, monitoring etc ... :)

**Comment by DerekGn** [comment]
Cool I will check out 1.0.3 and the new version.

**Comment by simpleidserver** [comment]
As promised, a new version of the CaseManagement project has been released.
The following changes have been made :
* An EntityFramework project is available here : https://github.com/simpleidserver/CaseManagement/tree/master/src/CaseManagement.CMMN.Persistence.EF
* The case engine has been redeveloped.
* An internal message broker is used to process domain events and external commands.

For more information you can contact us via gitter or GITHUB : https://gitter.im/simpleidserver/CaseManagement?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

In the next release, we are going to implement a BPMN workflow engine.
If you need other features, we can always include them in the next release.
